### ISSUE TITLE
Login not working anymore if the first one failed

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/ndb-core#31] opened 2016-08-19 18:00 UTC
Enter wrong credentials in the login. Should get an error message. After that the login doesn't work anymore even with the correct credentials. After the successful login, the app redirects to the login page again.

**Comment by liwde** [comment] 2018-07-19 18:16
I forgot to close this issue when I merged the pull request.
I verified again that the issue is actually resolved.

**Closed by liwde** 2018-07-19 18:16 UTC
Labels: Type: Bug
